use_frameworks!

target 'InterruptibleAction_Example' do
  pod 'InterruptibleAction', :path => '../'
  
  pod 'ReactiveSwift' 

  target 'InterruptibleAction_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.1'
    pod 'Nimble', '~> 7.1.3'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end
