use_frameworks!

target 'InterruptibleAction_Example' do
  pod 'InterruptibleAction', :path => '../'
  
  pod 'ReactiveSwift' 

  target 'InterruptibleAction_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
